title: Tolga Talha Yildiz
description: Here is my art, research and projects
author: "Tolga Talha Yildiz"

theme: minima


# Minima social links
twitter_username: tolgatalhayldz
instagram_username: tolgatalhayldz
github_username: ComicAddict
linkedin_username: tolga-talha-yildiz
#rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
